from pathlib import Path
import json,csv,sys,gzip
ROOT=Path(__file__).resolve().parents[1]
errors=[]
def req(p,keys):
    o=json.loads(p.read_text(encoding="utf-8"))
    for k in keys:
        if k not in o: errors.append(f"{p}: missing {k}")
    return o
src=req(ROOT/"data/metadata/sources.json",["jobvision","sanjesh_reference"])
sj=req(ROOT/"site/data/sanjesh_summary.json",["meta","byProvince","byDegree"])
if sj["meta"]["activeRowCount"]!=40534: errors.append("Sanjesh activeRowCount changed from audited reference")
if sj["meta"]["capacity"]!=602966: errors.append("Sanjesh capacity changed from audited reference")
if len(sj["byProvince"])!=31: errors.append("Province count != 31")
for p in [ROOT/"site/data/jobvision_metrics.json",ROOT/"site/data/matches.json"]:
    if not p.exists(): errors.append(f"missing {p}")
if errors:
    print("VALIDATION FAILED")
    print("\n".join(errors)); sys.exit(1)
print("VALIDATION PASSED")
print("No synthetic values are generated by the pipeline.")
